### ISSUE TITLE
HAUMPH custom command

### ISSUE THREAD

**Issue by EhlanaQueen** [danbopes/mtgbot-irc#4]
Basically they want with a count that uses 10 as the basis and resets daily."Haumph is getting in shape! 10 push-ups for every punt and sub/resub! Today's push-up count is %count%"

**Comment by danbopes** [comment]
You're going to have to clarify more than that.

What's the command name? !pushups?
Is this command going to be moderator or broadcaster only?
Can users get the count via like !pushupcount or something like that, which wont increment the counter?

I need to know exactly how it should be implemented.

**Comment by EhlanaQueen** [comment]
Command name will be !pushups. Is there a way that it can pull every punt inputted as well as subs/resubs to incrementally increase the counter so that they know how many pushups he needs to do for each item? It will probably need to be moderator only. It would be nice for viewers to be able to see the counter, but not necessary because it can be automated to output every so often on its own.

**Comment by danbopes** [comment]
OK, so here is what I'm thinking.

Command !pushups, available to everyone.

On a confirmed punt, (Tell him about !puntthreshold, and set it accordingly), it will add 10 pushups to the counter. On a resub, or sub, it will also add another 10 pushups. (Please let me know how I should change the sub message accordingly, if you want to include his pushups in there.)

When he does the pushups, he can use !resetpushups, or !setpushups <number> to set the new amount, (Does he do them in spurts, or always all at once). I think !setpushups just covers everything here, but feel free to chime in.

What do you think @undervoltage ?

**Comment by EhlanaQueen** [comment]
!resetpushups would take care of the daily reset. he does them in spurts so having a command to set the number would also be appreciated. Other than that everything looks good. Although I though the !puntthreshold command was for how many people was needed to confirm the initial punt. I do not know.

**Comment by EhlanaQueen** [comment]
Asked in chat and if it is implemented as you stated all will be kosher. Thank you Daniel.

**Comment by danbopes** [comment]
> (Please let me know how I should change the sub message accordingly, if you want to include his pushups in there.)
> 
> I do not know.

What do you not know? If he has no or very low threshold, then punts would get easily added, and it would increment his pushup counter for potentially non punts. Find a good number and talk with him, and then set it.

**Comment by EhlanaQueen** [comment]
Okay.

**Comment by danbopes** [comment]
> (Please let me know how I should change the sub message accordingly, if you want to include his pushups in there.)

^ I still need to know what the sub message should be changed to.

**Comment by EhlanaQueen** [comment]
I would say leave it the same as it is now. The !pushups command will take care of letting them know about how subs effects it.

**Comment by EhlanaQueen** [comment]
Will you let me know when it is done so I can send the mods the commands. Thanks again.

**Comment by danbopes** [comment]
Please see https://bitbucket.org/danbopes/mtgbot/issues/4/haumph-custom-command
