### ISSUE TITLE
!giveaway command should be broadcaster only

### ISSUE THREAD

**Issue by undervoltage** [danbopes/mtgbot-irc#8]
right now it is mod only. I don't forsee a situation where a moderator would initiate a giveaway, however it has accidentally been done once already.

```
Possible Bot Request from 'dross19' in channel g3rryt: !giveaway Kappa
```

11:35 DRoss19: I dun goofed hard
11:35 DRoss19: but it was HILARIOUS
11:36 DRoss19: hey man in my defense I didn't actually think I could do that

**Comment by danbopes** [comment]
This was done for moderators who like to assist broadcasters. I have seen a few mods like to help out in this capacity, and there isn't a huge downside to this. The broadcaster can always reset the giveaway, so I don't see a big reason to change this.
